language: python
python:
  - "3.5"
sudo: required

notifications:
  email:
    recipients:
      sbadillo@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

branches:
  only:
  - sources

env:
  global:
    secure: "jZWVAdB7VWaPFHr98DW3fIwLxJIOxECnOR0Bw0OMeLAnO+5qmsxwB2LVK57ymxt956jJN/YkPH8I6aiTTbrYKS2ZWiI4KdnD8XvR81QkSDzdOrF785Ri7KCfRa9X2spi2GeluRfVRHQp1PZ+jGn7+FrrMePa64U+huZuYtBMGgsSXobciV2KBVGo6xVuYJdr8UFiPgtNycmpaWOqdugIljhWG2g/Q7rjfaMkE93VMhHLF3W3Eg0X3HH/p5ayU1VHyZtYCYGMuKUYJVAodSbi9+KLCn+pGRJxjJHGaxNFHJjTKxxa2/JTM5Bv5IhhBPks381ZcjU+t9Mjt0kdYgx5k1Y8CAYq51E2sxRmD1Qy4TqI7IaoBlTnQ2vNzhi7fNCWH/v1VEyDQ2n0J/LE0g8rC4NUkhhBGC8t/ZPxVorf9Y+cqXhC77TQPk+SPm4efGu9j7jwwIWNo83cdNt2ELpvKlNKh3qX0rMdOSTxnpUG59AslLHVMw4PT5PXPLUFK+qGXeLjir+b4GBbDbn2hbZAeIBx+tFx99eOJuX66sONBGASThVOsMLnPr8j+d4TdbFzN6qNLS8X44ku7z0g6jYEXM1Y/kEkqHUisBAYO9BnuxM18cEFqUzKrpf90Dp3DQ/C+bBVZwprACY5OYVTR4Nb12TkiPJ1FwDZJ6GYCcPdpa0="

install:
- pip install -r requirements.txt
   
script:

- make publish github
